

on: [push]
jobs:
  buid:
    runs-on: ubuntu-latest
    env:
        working-directory: ./GiftcardSite
        
    steps:
      - uses: actions/checkout@master
      -  working-directory: ${{env.working-directory}}
      - run: pip install django
      - run: pip install django_cryptography
      - run: python manage.py makemigrations LegacySite
      - run: python manage.py makemigrations
      - run: python manage.py migrate
      - run: sh import_dbs.sh
      - run: python manage.py test
          
