

on: [push]
jobs:
  buid:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@main
      - run: pwd
      - run: ls -l
      - run: |
          pwd
          cd GiftcardSite
          cd LegacySite
      - run: pwd
      - run: python manage.py test
          
