

on: [push]
jobs:
  buid:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@main
      - run: pwd
      - run: ls -l
      - run python install Django
      - run: python GiftcardSite/manage.py test
          
